export const USER_SIGN_IN_STATUS = "USER_SIGN_IN_STATUS"
export const USER_SIGN_IN_RESPONSE = "USER_SIGN_IN_RESPONSE"
export const USER_SIGN_IN_FAILED = 'USER_SIGN_IN_FAILED'

export const USER_LOGIN_STATUS = "USER_LOGIN_STATUS"
export const USER_LOGIN_RESPONSE = "USER_LOGIN_RESPONSE"
export const USER_LOGIN_ERROR = "USER_LOGIN_ERROR"

export const GET_ALL_ROOM_STATUS = "GET_ALL_ROOM_STATUS"
export const GET_ALL_ROOM_RESPONSE = "GET_ALL_ROOM_RESPONSE"
export const GET_ALL_ROOM_ERROR = "GET_ALL_ROOM_ERROR"

export const REGISTER_ROOM_STATUS  = "REGISTER_ROOM_STATUS"
export const REGISTER_ROOM_RESPONSE = "REGISTER_ROOM_RESPONSE"
export const REGISTER_ROOM_ERROR = "REGISTER_ROOM_ERROR"

export const UPLOAD_ROOM_IMAGE_STATUS = "UPLOAD_ROOM_IMAGE_STATUS"
export const UPLOAD_ROOM_IMAGE_RESPONSE = "UPLOAD_ROOM_IMAGE_RESPONSE"
export const UPLOAD_ROOM_IMAGE_ERROR = "UPLOAD_ROOM_IMAGE_ERROR"

export const ADD_TO_BOOKING_LIST = "ADD_TO_BOOKING_LIST"
export const ADD_TO_BOOKING_LIST_RESPONSE = "ADD_TO_BOOKING_LIST_RESPONSE"
export const ADD_TO_BOOKING_LIST_ERROR = "ADD_TO_BOOKING_LIST_ERROR"

export const GET_ADDED_LIST_STATUS = "GET_ADDED_LIST_STATUS"
export const GET_ADDED_LIST_RESPONSE = "GET_ADDED_LIST_RESPONSE"
export const GET_ADDED_LIST_ERROR = "GET_ADDED_LIST_ERROR"

//reset the password
export const RESET_PASSWORD = "RESET_PASSWORD"
export const RESET_PASSWORD_RESPONSE = "RESET_PASSWORD_RESPONSE"
export const RESET_PASSWORD_ERROR = "RESET_PASSWORD_ERROR"